spring.application.name=transaction-engine

# 1. Database Connection String
# Note: We change 'postgresql://' to 'jdbc:postgresql://' so Java knows how to handle it
spring.datasource.url=jdbc:postgresql://ep-shiny-water-aojztt81-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UNnkCTE9qJH5
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate Settings
# 'update' means Hibernate will create/update your database tables automatically 
spring.jpa.hibernate.ddl-auto=update
# This prints the SQL Hibernate generates to your terminal (great for learning!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Server Port (Standard for Spring Boot)
server.port=8080